name: Build and Upload Artifacts

on: [push, pull_request]

jobs:
  CreateArtifact:
    runs-on: self-hosted
    steps:
      - name: Create artifacts Directory
        run:  mkdir artifacts
      - name: Create file
        run:  echo Hello World > "./artifacts/hello.txt"
      - uses: actions/upload-artifact@v3
        with: 
          name: 'hello'
          path: './artifacts/hello.txt'
      