name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code from the repository
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run:  dotnet restore
      - name: Build
        run:  dotnet build --no-restore
      - name: Test
        run:  dotnet test --no-build --verbosity normal
      - name: Publish
        run:  dotnet publish -c Release -o dotnetcorewebapp
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: "./dotnetcorewebapp"
