name: Variable Demo

on: [ push ]  


env:
  user_name: "Manny"
  demo_name: "Variable Demo"


jobs:

  VariableUsageJob:
    runs-on: ubuntu-latest
    env:
      job_var1: "job variable value"
    steps:
      - name: Using Workflow Variables
        run: echo Hello, $user_name!
             Welcome to $demo_name!!!
             here is job var1 $job_var1
             here is step var1 $step_var1
        env: 
          step_var1: "Step Variable Value"

      - name: Set user_name Variable
        run:  echo "::set-env name=User_name::Caleb"

      - name:  Set new_var Variable
        run: echo "::set-env name=new_var::newvarvalue"

      - name: Using Variables
        run: echo Hello, $user_name!
              Welcome to $demo_name!!!
              here ise job var1 $job_var1
              here is new_var $new_var